site_name: Asagg
repo_url: https://github.com/pedroaba/asagg
repo_name: predoaba/asagg

theme:
  name: material
  logo: assets/icon.png
  favicon: assets/icon.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [asagg_lib]
